### ISSUE TITLE
Term code delete button is not inline

### ISSUE THREAD

**Issue by kkardatos** [endeavourhealth-discovery/IMDirectory#1295]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Z0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb03576ac23ec397b0f9a46bf0f2277735b74839/Screenshot%20%281%29.png)

**Comment by matt-voror** [comment]
Button is in line. Other items just don't have a title.
