### ISSUE TITLE
Set Creator - Retains screen and crashes

### ISSUE THREAD

**Issue by DavidStables** [endeavourhealth-discovery/IMDirectory#1406]
User - Folder-> rt click-< new ->Concept set -> edit concept set- >Create  -> View in IM
Problem : View in IM launches view (correct), edit screen is retained. Tab back to edit screen which is the same and select "create" again. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3eb4d19084f55c49ea4c232470db1cc2ae24abc2/image.png)

**Comment by VororRich** [comment]
Proposal: Navigate to new concept WITHIN tab, rather than opening a new one (thereby rendering this one useless)
