### ISSUE TITLE
Set creation - no folder > marker

### ISSUE THREAD

**Issue by DavidStables** [endeavourhealth-discovery/IMDirectory#1415]
User : select folder -> new -> concept set ...... -> create
Problem: Folder has no indication of an set existing although is shown when folder is selected. F5 needed to refresh
Solution : As per the folder display issue #1412 should refresh with folder open

**Comment by VororRich** [comment]
May be worth brainstorming a solution to this one as the initial director tab will have no reference/notification that the creator tab was successful or closed (therefore will not "know" to refresh).  Sledgehammer approach would be to refresh the tree on window activation.

**Comment by kkardatos** [comment]
Another way to dodge this problem is to open the creator on the same window instead of a new window. When the user will click on 'open in Viewer' after the creation of the entity, the tree should be updated.
