### ISSUE TITLE
Add selection here a bit odd

### ISSUE THREAD

**Issue by DavidStables** [endeavourhealth-discovery/IMDirectory#1417]
User :right clicked a folder and "add selection" here
Problem : says "do you want to move undefined to xxx"
Solution : should allow that selection

User : click a folder XXX -> "add selection here"
Problem : says "do you want to add XXX to XXX"
Solution: should not be allowed to add XXX to XXX  (although does give an error if you try)

**Comment by VororRich** [comment]
"Undefined" suggests no current selection, in which case the menu option should be disabled.

Cursory check whether item is being added to itself should be possible.  Subsequent error is to ensure this does not happen down a  number of levels of nesting (i.e adding a selection to a great great grandchild of itself)
