### ISSUE TITLE
Support inclusion of other sets within sets

### ISSUE THREAD

**Issue by VororRich** [endeavourhealth-discovery/IMDirectory#1457]
Allow for creation, display and expansion of a set defined as
* Include SNOMED Blood Pressure Set
* Exclude Patient Recorded concept
* Add in (via ECL) Home BP (emis local code)

Current thinking (pseudo IMQ): -
match: [
  match: { inSet: SNOMED_BP, Exclude: PatientRecorded }
  match: { << EMISHomeBP }
]

UI: -
* Top section to display inSet & exclusion (first match)
* Bottom section to display ECL (second matc)

**Comment by matt-voror** [comment]
Parent set to be able to add children sets. Sets added as inclusions from parent will need updated individually to add parent as isSubsetOf. Parent does not add anything to entity json.
