### ISSUE TITLE
Data model builder should find xsd datatypes for populating the range of values

### ISSUE THREAD

**Issue by kkardatos** [endeavourhealth-discovery/IMDirectory#2109]
<img width="1541" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2U4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20c36bcb92356ed061ff14db741d70a0de064610/image.png" alt="image.png" />

**Comment by matt-voror** [comment]
xsd number does not exist. See list of valid number types:

![image](https://github.com/user-attachments/assets/0dc29f49-3f87-4379-a4df-4addb8f85ac7)

**Comment by kkardatos** [comment]
Created ticket #2130 and closed this one.
