### ISSUE TITLE
502 error on detailsDisplay

### ISSUE THREAD

**Issue by ZeynepBayazitoglu** [endeavourhealth-discovery/IMDirectory#290]
**Describe the bug**
502 error on detailsDisplay

**To Reproduce**
1. Go to 'https://dev.endhealth.co.uk/#/directory/folder/http:%2F%2Fendhealth.info%2Fim%23903031000252104'
4. See error on the Network

**Comment by VororRich** [comment]
Issue was due to node_api not running.
