### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by VororRich** [endeavourhealth-discovery/IMDirectory#304]

**Comment by DavidStables** [comment]
The follow in ecl prodiuces a 500 error
<<763158003 | Medicinal Product |:
	<<127489000|has active ingredient |= <<698090000 | Apixaban (substance) |
          OR <<127489000|has active ingredient| = <<442031002 | Rivaroxaban (substance)|
          OR <<127489000|has active ingredient|= << 698871007| Dabigatran (substance)|
          OR <<127489000|has active ingredient|= << 712778008| Edoxaban (substance)|
          OR <<127489000|has active ingredient|= << 387260007| Phenindione (substance) | 
          OR <<127489000|has active ingredient|= << 59488002 | Warfarin sodium (substance) | 
          OR <<127489000|has active ingredient|= << 372756006| Warfarin (substance)|
